# Generated by Django 5.2.7 on 2025-10-22 10:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedString',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=500, unique=True)),
                ('length', models.IntegerField()),
                ('is_palindrome', models.BooleanField()),
                ('unique_characters', models.IntegerField()),
                ('word_count', models.IntegerField()),
                ('character_frequency_map', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Analyzed String',
                'indexes': [models.Index(fields=['is_palindrome'], name='analyzer_an_is_pali_7bf271_idx'), models.Index(fields=['length'], name='analyzer_an_length_a26b5c_idx'), models.Index(fields=['word_count'], name='analyzer_an_word_co_0dc9e5_idx'), models.Index(fields=['value'], name='analyzer_an_value_77b206_idx')],
            },
        ),
    ]
